apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
data:
  GREETING: Hello from hello-service
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "postgresql://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  POSTGRES_HOST: {{ include "postgresql.fullname" . | b64enc | quote }}
  POSTGRES_PORT: {{ .Values.postgresql.service.port | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
