apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
  labels:
    app: postgres
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: myapp
  POSTGRES_USER: myuser
  POSTGRES_HOST_AUTH_METHOD: trust
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dk

