apiVersion : extensions/v1beta1
kind : Ingress
metadata :
  name : hello-service-ingress
  annotations :
    nginx.ingress.kubernetes.io/rewrite-target : /$1
spec :
  rules :
  - host : arch.homework
    http :
      paths :
      - path : /otusapp/svkrivonos/(.*)
        backend :
          serviceName : hello-service
          servicePort : 8000
