apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello-service-app
  ports:
  - name: http
    port: 8000
    targetPort: 8080
    protocol: TCP
  type: NodePort
