apiVersion: v2
name: hello-service-chart
description: A Helm chart for Kubernetes

type: application

version: 0.1.0
appVersion: 1.2.0

dependencies:
  - name: postgresql
    version: 9.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - myapp-database